### ISSUE TITLE
Upgrade the Login and Signup Page

### ISSUE THREAD

**Issue by Sagar-developer** [Sagar-developer/hospital-management-system#1]
I Want The People From Open-Source Community To Collab With Me In This Project
Please Upgrade The Login and Sign-Up Page For New User Signing and Login

**Comment by prathameshbhor123** [comment]
Hi Sagar i want to contribute to your project. I will make nearby hospital page.

**Comment by Siddharth519** [comment]
Hii Sagar, I am ready to contribute to your project. I can make the different login and sign up page
